(ns sixsq.nuvla.ui.components.job-cell-scenes
  (:require [sixsq.nuvla.ui.portfolio-utils :refer [defscene]]
            [sixsq.nuvla.ui.common-components.job.views :refer [JobCell]]))

(defscene basic
          [JobCell {:status-message "hello-world"}])

(defscene basic-long-status-message
          [JobCell {:status-message "Exception-Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/job/executor/executor.py\", line 57, in process_job\n    return_code = action_instance.do_work()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/job/actions/deployment_state.py\", line 59, in do_work\n    raise ex\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/job/actions/deployment_state.py\", line 54, in do_work\n    self.get_application_state()\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/job/actions/deployment_state.py\", line 34, in get_application_state\n    services = connector.get_services(Deployment.uuid(self.deployment),\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/connector/connector.py\", line 16, in wrapper\n    raise e\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/connector/connector.py\", line 14, in wrapper\n    result = f(self, *f_args, **f_kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/connector/docker_stack.py\", line 187, in get_services\n    return self._stack_services(name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/connector/docker_stack.py\", line 182, in _stack_services\n    for service in execute_cmd(cmd).stdout.splitlines()]\n                   ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/nuvla/job_engine/connector/utils.py\", line 90, in execute_cmd\n    raise Exception(result.stderr)\nException: Get \"https://10.0.128.103:2376/v1.44/services?filters=%7B%22label%22%3A%7B%22com.docker.stack.namespace%3Dc050e406-389d-4ce5-bce0-eb5c1551106d%22%3Atrue%7D%7D&status=true\": dial tcp 10.0.128.103:2376: i/o timeout\n\n"}])

(defscene coe-resource-actions-fail-parsing
          [JobCell {:action         "coe_resource_actions"
                    :status-message "status message that fail to be parsed as json should be rendered as default"}])

(defscene coe-resource-actions-missing-docker-entry
          [JobCell {:action         "coe_resource_actions"
                    :status-message "{\"msg\": \"json but not docker key inside rendered also as default\"}"}])

(defscene coe-resource-actions-single-success
          [JobCell {:status-message
                    "{\n    \"docker\": [\n        {\n            \"success\": true,\n            \"return-code\": 200,\n            \"message\": \"Image hello-world:latest was already present and updated\"\n        }\n    ]\n}",
                    :id     "job/e4986f52-dadb-4ecf-8119-6de5a978cdf5"
                    :action "coe_resource_actions"}])

(defscene coe-resource-actions-multiple-errors
          [JobCell {:status-message
                    "{\n    \"docker\": [\n        {\n            \"success\": false,\n            \"return-code\": 403,\n            \"content\": \"403 Client Error for http+docker://localhost/v1.42/networks/085f8229d6dd9b9e7e99513bfd6c20f35c75057382f6d5c119e1d29a1172c667: Forbidden (\\\"none is a pre-defined network and cannot be removed\\\")\",\n            \"message\": \"Operation not supported for network -- 085f8229d6dd9b9e7e99513bfd6c20f35c75057382f6d5c119e1d29a1172c667\"\n        },\n        {\n            \"success\": false,\n            \"return-code\": 403,\n            \"content\": \"403 Client Error for http+docker://localhost/v1.42/networks/cd4adbc05d7daa22be710a7c2e43a7242d9e212a5be66fb917261dd387911f5f: Forbidden (\\\"host is a pre-defined network and cannot be removed\\\")\",\n            \"message\": \"Operation not supported for network -- cd4adbc05d7daa22be710a7c2e43a7242d9e212a5be66fb917261dd387911f5f\"\n        },\n        {\n            \"success\": false,\n            \"return-code\": 400,\n            \"content\": \"400 Client Error for http+docker://localhost/v1.42/networks/maxhxtw6fs8lvji11gtvhml3y: Bad Request (\\\"rpc error: code = FailedPrecondition desc = ingress network cannot be removed because service 1hnbk87zpcbc3754qfhksa5iq depends on it\\\")\",\n            \"message\": \"Unknown error: {\\\"message\\\":\\\"rpc error: code = FailedPrecondition desc = ingress network cannot be removed because service 1hnbk87zpcbc3754qfhksa5iq depends on it\\\"}\\n\"\n        },\n        {\n            \"success\": false,\n            \"return-code\": 403,\n            \"content\": \"403 Client Error for http+docker://localhost/v1.42/networks/cb0f0eff592ea8f6cafa11e31e3c824c2e2ec4d22fc91511090bf59b82f5a418: Forbidden (\\\"error while removing network: network docker_gwbridge id cb0f0eff592ea8f6cafa11e31e3c824c2e2ec4d22fc91511090bf59b82f5a418 has active endpoints\\\")\",\n            \"message\": \"Operation not supported for network -- cb0f0eff592ea8f6cafa11e31e3c824c2e2ec4d22fc91511090bf59b82f5a418\"\n        },\n        {\n            \"success\": false,\n            \"return-code\": 403,\n            \"content\": \"403 Client Error for http+docker://localhost/v1.42/networks/95eabb9db13dde00285c0f384b0e8e12a796b69ef3ef7ae7f5ccbd1f68b4908f: Forbidden (\\\"bridge is a pre-defined network and cannot be removed\\\")\",\n            \"message\": \"Operation not supported for network -- 95eabb9db13dde00285c0f384b0e8e12a796b69ef3ef7ae7f5ccbd1f68b4908f\"\n        },\n        {\n            \"success\": false,\n            \"return-code\": 400,\n            \"content\": \"400 Client Error for http+docker://localhost/v1.42/networks/r5ka10cb2l7qm9sd9815ih9ke: Bad Request (\\\"rpc error: code = FailedPrecondition desc = network r5ka10cb2l7qm9sd9815ih9ke is in use by service 1d7qsrxflszhgv3pq5maa3a62\\\")\",\n            \"message\": \"Unknown error: {\\\"message\\\":\\\"rpc error: code = FailedPrecondition desc = network r5ka10cb2l7qm9sd9815ih9ke is in use by service 1d7qsrxflszhgv3pq5maa3a62\\\"}\\n\"\n        }\n    ]\n}",
                    :id     "job/e4986f52-dadb-4ecf-8119-6de5a978cdf5"
                    :action "coe_resource_actions"}])

